#!/usr/bin/env python3
# encoding: utf-8

# we could also use twitter pex

import os
import sys
import glob
import zipapp

FOLDER = os.path.dirname(os.path.realpath(__file__))
IMPORT = os.path.abspath(os.path.join(FOLDER, 'lib'))
if not os.path.exists(IMPORT):
	sys.exit(f'could not import "{IMPORT}"')

sys.path.append(IMPORT)
from vyosextra.insource import generate
from vyosextra.insource import location

if __name__ == '__main__':
	here = os.path.dirname(os.path.realpath(__file__))
	folder = os.path.abspath(os.path.join(here, 'data'))

	generate(folder)

	zipapp.create_archive(
		source='lib',
		target='./vyos',
		interpreter='/usr/bin/python3',
		main='vyosextra.entry:vyos',
		compressed=True,
	)

	os.remove(location())
